version: '2'

services:
  frontend-svelte-go:
    container_name: frontend-svelte-go
    image: frontend-svelte-go:0.0.1
    build: .
    volumes:
    - ./svelte:/app/svelte
    ports:
      - 7071:7071
    environment:
      PATH_API: http://toto-api-go:7071/
    restart: always